name: Run Tests in Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Apply Kubernetes Pod Configuration
        run: kubectl apply -f KubernetesPod.yaml

      - name: Wait for Pod to Be Ready
        run: |
          kubectl wait --for=condition=ready pod -l app=gradle --timeout=300s

      - name: Run Tests Inside the Pod
        run: |
          kubectl exec -it $(kubectl get pod -l app=gradle -o jsonpath="{.items[0].metadata.name}") -- ./gradlew test

      - name: Cleanup Kubernetes Pod
        if: always()
        run: kubectl delete -f KubernetesPod.yaml
